"""
Cafe Inspiration Bank — v1 seed data (Part 2).

12 design-family records for business_type="cafe". Each is a reusable
LAYOUT/STYLE PATTERN, not a copy of any specific real website. reference_url
is omitted (internal research field only, never required) to keep this
seed set focused purely on the design metadata the builder actually uses.

Families included (per spec):
  cafe_specialty_store, cafe_minimal_clean, cafe_luxury_premium,
  cafe_warm_handmade, cafe_food_bakery, cafe_local_simple,
  cafe_gallery_focused, cafe_reservation_focused
plus 4 additional variations for real diversity within those families.
"""
from __future__ import annotations

from app.inspiration.models import InspirationReference


CAFE_INSPIRATION_BANK: list[InspirationReference] = [

    InspirationReference(
        reference_id="cafe_warm_handmade_01",
        job_category="website_builder",
        business_type="cafe",
        reference_name="گرم و صمیمی",
        visual_style="warm_handmade",
        layout_type="story_driven_menu",
        color_palette={"primary": "#92400E", "secondary": "#D4A574", "accent": "#F59E0B"},
        hero_style="split_text_image",
        navigation_style="sticky_simple",
        card_style="rounded_shadow",
        section_structure=["navbar", "hero", "about", "menu_grid", "gallery", "benefits", "form", "footer"],
        interaction_style="subtle_hover",
        best_for=["گرم", "صمیمی", "دست‌ساز", "خانگی", "محلی"],
        inspiration_notes="حس یک کافه محلی با روایت داستانی قبل از منو — مناسب کافه‌هایی که می‌خواهند ابتدا با مشتری ارتباط انسانی بسازند.",
        tags=["warm", "cozy", "handmade", "story-first", "local"],
        editable_layer_requirements=["section", "card", "image_box", "icon_image", "title", "description", "price", "button"],
        freshness_score=0.7, design_quality_score=0.8, industry_match_score=0.9,
        uniqueness_score=0.6, popularity_score=0.6,
        estimated_audience_level="moderate", brand_popularity="known", social_presence="medium",
    ),

    InspirationReference(
        reference_id="cafe_minimal_clean_01",
        job_category="website_builder",
        business_type="cafe",
        reference_name="ساده و مینیمال",
        visual_style="minimal_clean",
        layout_type="centered_grid",
        color_palette={"primary": "#1F2937", "secondary": "#F3F4F6", "accent": "#6B7280"},
        hero_style="centered_minimal",
        navigation_style="transparent_overlay",
        card_style="flat_bordered",
        section_structure=["navbar", "hero", "menu_grid", "about", "form", "footer"],
        interaction_style="minimal_static",
        best_for=["ساده", "مینیمال", "مدرن", "تمیز"],
        inspiration_notes="فضای سفید زیاد، تایپوگرافی قوی، بدون شلوغی بصری — برای مخاطبی که سادگی و وضوح می‌خواهد.",
        tags=["minimal", "clean", "modern", "typography-focused"],
        editable_layer_requirements=["section", "card", "image_box", "icon_image", "title", "description", "price", "button"],
        freshness_score=0.85, design_quality_score=0.85, industry_match_score=0.75,
        uniqueness_score=0.5, popularity_score=0.7,
        estimated_audience_level="moderate", brand_popularity="known", social_presence="medium",
    ),

    InspirationReference(
        reference_id="cafe_luxury_premium_01",
        job_category="website_builder",
        business_type="cafe",
        reference_name="لوکس و خاص",
        visual_style="luxury_premium",
        layout_type="full_bleed_hero",
        color_palette={"primary": "#1F2937", "secondary": "#92400E", "accent": "#D4A574"},
        hero_style="large_image_overlay",
        navigation_style="centered_logo",
        card_style="image_focused",
        section_structure=["navbar", "hero", "about", "gallery", "menu_grid", "benefits", "form", "footer"],
        interaction_style="scroll_reveal",
        best_for=["لوکس", "خاص", "گرانقیمت", "حرفه‌ای"],
        inspiration_notes="هرو تمام‌عرض با تصویر بزرگ، فاصله‌گذاری سخاوتمندانه، تأکید روی کیفیت بالا و تجربه اختصاصی.",
        tags=["luxury", "premium", "elegant", "full-bleed"],
        editable_layer_requirements=["section", "card", "image_box", "icon_image", "title", "description", "price", "button"],
        freshness_score=0.75, design_quality_score=0.9, industry_match_score=0.8,
        uniqueness_score=0.75, popularity_score=0.5,
        estimated_audience_level="niche", brand_popularity="known", social_presence="medium",
    ),

    InspirationReference(
        reference_id="cafe_specialty_store_01",
        job_category="website_builder",
        business_type="cafe",
        reference_name="فروشگاهی و محصول‌محور",
        visual_style="product_commerce",
        layout_type="catalog_grid",
        color_palette={"primary": "#92400E", "secondary": "#F59E0B", "accent": "#1F2937"},
        hero_style="split_text_image",
        navigation_style="sticky_simple",
        card_style="image_focused",
        section_structure=["navbar", "hero", "menu_grid", "benefits", "gallery", "form", "footer"],
        interaction_style="subtle_hover",
        best_for=["سفارش", "خرید", "فروش", "محصول", "آنلاین"],
        inspiration_notes="منو/محصولات با قیمت برجسته و دکمه انتخاب روی هر کارت — شبیه یک فروشگاه کوچک قهوه، نه فقط معرفی.",
        tags=["ecommerce-like", "product-grid", "price-forward"],
        editable_layer_requirements=["section", "card", "image_box", "icon_image", "title", "description", "price", "button"],
        freshness_score=0.7, design_quality_score=0.75, industry_match_score=0.95,
        uniqueness_score=0.55, popularity_score=0.65,
        estimated_audience_level="moderate", brand_popularity="known", social_presence="medium",
    ),

    InspirationReference(
        reference_id="cafe_food_bakery_01",
        job_category="website_builder",
        business_type="cafe",
        reference_name="نان و شیرینی‌محور",
        visual_style="bakery_warm",
        layout_type="hero_grid_menu",
        color_palette={"primary": "#B45309", "secondary": "#FBBF24", "accent": "#92400E"},
        hero_style="split_text_image",
        navigation_style="sticky_simple",
        card_style="rounded_shadow",
        section_structure=["navbar", "hero", "menu_grid", "about", "gallery", "form", "footer"],
        interaction_style="subtle_hover",
        best_for=["نانوایی", "شیرینی", "صبحانه", "کیک"],
        inspiration_notes="کارت‌های منو با تأکید بصری بر تنوع محصولات نان/شیرینی — رنگ‌های گرم نان تازه.",
        tags=["bakery", "pastry", "breakfast", "warm-tones"],
        editable_layer_requirements=["section", "card", "image_box", "icon_image", "title", "description", "price", "button"],
        freshness_score=0.7, design_quality_score=0.75, industry_match_score=0.85,
        uniqueness_score=0.5, popularity_score=0.6,
        estimated_audience_level="moderate", brand_popularity="known", social_presence="medium",
    ),

    InspirationReference(
        reference_id="cafe_local_simple_01",
        job_category="website_builder",
        business_type="cafe",
        reference_name="محلی و ساده",
        visual_style="local_practical",
        layout_type="info_first",
        color_palette={"primary": "#16A34A", "secondary": "#F3F4F6", "accent": "#92400E"},
        hero_style="centered_minimal",
        navigation_style="sticky_simple",
        card_style="flat_bordered",
        section_structure=["navbar", "hero", "menu_grid", "form", "footer"],
        interaction_style="minimal_static",
        best_for=["محلی", "آدرس", "شعبه", "نزدیک", "سریع"],
        inspiration_notes="کوتاه و کاربردی — آدرس/تماس و منو در دسترس سریع، بدون بخش‌های اضافه تزئینی.",
        tags=["local", "practical", "short", "address-forward"],
        editable_layer_requirements=["section", "card", "image_box", "icon_image", "title", "description", "price", "button"],
        freshness_score=0.6, design_quality_score=0.65, industry_match_score=0.8,
        uniqueness_score=0.45, popularity_score=0.55,
        estimated_audience_level="niche", brand_popularity="emerging", social_presence="low",
    ),

    InspirationReference(
        reference_id="cafe_gallery_focused_01",
        job_category="website_builder",
        business_type="cafe",
        reference_name="تصویری و فضامحور",
        visual_style="visual_storytelling",
        layout_type="gallery_first",
        color_palette={"primary": "#1F2937", "secondary": "#D4A574", "accent": "#92400E"},
        hero_style="large_image_overlay",
        navigation_style="transparent_overlay",
        card_style="image_focused",
        section_structure=["navbar", "hero", "gallery", "about", "menu_grid", "form", "footer"],
        interaction_style="scroll_reveal",
        best_for=["عکس", "فضا", "محیط", "دکوراسیون", "اتمسفر"],
        inspiration_notes="گالری بزرگ زود در صفحه، قبل از منو — برای کافه‌هایی که فضای فیزیکی نقطه قوت‌شان است.",
        tags=["gallery-first", "ambience", "visual", "interior"],
        editable_layer_requirements=["section", "card", "image_box", "icon_image", "title", "description", "price", "button"],
        freshness_score=0.8, design_quality_score=0.8, industry_match_score=0.75,
        uniqueness_score=0.65, popularity_score=0.6,
        estimated_audience_level="moderate", brand_popularity="known", social_presence="high",
    ),

    InspirationReference(
        reference_id="cafe_reservation_focused_01",
        job_category="website_builder",
        business_type="cafe",
        reference_name="رزرومحور",
        visual_style="service_focused",
        layout_type="reservation_first",
        color_palette={"primary": "#7C3AED", "secondary": "#F3F4F6", "accent": "#1F2937"},
        hero_style="split_text_image",
        navigation_style="sticky_simple",
        card_style="rounded_shadow",
        section_structure=["navbar", "hero", "form", "menu_grid", "gallery", "about", "footer"],
        interaction_style="subtle_hover",
        best_for=["رزرو", "میز", "نشستن", "مهمانی", "رویداد"],
        inspiration_notes="فرم رزرو میز نزدیک به بالای صفحه، قبل از منو — اولویت با اقدام رزرو، نه فقط مرور محتوا.",
        tags=["reservation-first", "booking", "form-prominent"],
        editable_layer_requirements=["section", "card", "image_box", "icon_image", "title", "description", "price", "button"],
        freshness_score=0.7, design_quality_score=0.75, industry_match_score=0.85,
        uniqueness_score=0.6, popularity_score=0.55,
        estimated_audience_level="moderate", brand_popularity="known", social_presence="medium",
    ),

    InspirationReference(
        reference_id="cafe_minimal_clean_02",
        job_category="website_builder",
        business_type="cafe",
        reference_name="مدرن و سبک",
        visual_style="minimal_clean",
        layout_type="hero_grid_menu",
        color_palette={"primary": "#2563EB", "secondary": "#F3F4F6", "accent": "#1F2937"},
        hero_style="centered_minimal",
        navigation_style="sticky_simple",
        card_style="flat_bordered",
        section_structure=["navbar", "hero", "menu_grid", "benefits", "form", "footer"],
        interaction_style="minimal_static",
        best_for=["مدرن", "جوان", "ساده", "سریع"],
        inspiration_notes="نسخه‌ای سردتر و آبی‌تر از مینیمال کلاسیک — برای برندهای کافه با حس تکنولوژیک‌تر.",
        tags=["minimal", "modern", "cool-palette", "youthful"],
        editable_layer_requirements=["section", "card", "image_box", "icon_image", "title", "description", "price", "button"],
        freshness_score=0.85, design_quality_score=0.8, industry_match_score=0.7,
        uniqueness_score=0.55, popularity_score=0.65,
        estimated_audience_level="moderate", brand_popularity="emerging", social_presence="medium",
    ),

    InspirationReference(
        reference_id="cafe_warm_handmade_02",
        job_category="website_builder",
        business_type="cafe",
        reference_name="روستیک و طبیعی",
        visual_style="warm_handmade",
        layout_type="story_driven_menu",
        color_palette={"primary": "#65A30D", "secondary": "#D4A574", "accent": "#92400E"},
        hero_style="split_text_image",
        navigation_style="sticky_simple",
        card_style="rounded_shadow",
        section_structure=["navbar", "hero", "about", "gallery", "menu_grid", "form", "footer"],
        interaction_style="subtle_hover",
        best_for=["طبیعی", "ارگانیک", "روستیک", "گیاهی"],
        inspiration_notes="رنگ‌های سبز و خاکی، تأکید بر مواد اولیه طبیعی و فضای روستیک/چوبی.",
        tags=["rustic", "organic", "natural", "earthy"],
        editable_layer_requirements=["section", "card", "image_box", "icon_image", "title", "description", "price", "button"],
        freshness_score=0.65, design_quality_score=0.75, industry_match_score=0.8,
        uniqueness_score=0.6, popularity_score=0.5,
        estimated_audience_level="niche", brand_popularity="emerging", social_presence="medium",
    ),

    InspirationReference(
        reference_id="cafe_luxury_premium_02",
        job_category="website_builder",
        business_type="cafe",
        reference_name="تیره و شیک",
        visual_style="luxury_premium",
        layout_type="full_bleed_hero",
        color_palette={"primary": "#111827", "secondary": "#D4A574", "accent": "#7C3AED"},
        hero_style="large_image_overlay",
        navigation_style="centered_logo",
        card_style="image_focused",
        section_structure=["navbar", "hero", "menu_grid", "about", "gallery", "form", "footer"],
        interaction_style="scroll_reveal",
        best_for=["لوکس", "شبانه", "خاص", "تیره"],
        inspiration_notes="پالت تیره با لهجه طلایی/بنفش — حس کافه/بار شبانه شیک‌تر، نه کافه روزانه معمولی.",
        tags=["dark-mode", "luxury", "evening", "moody"],
        editable_layer_requirements=["section", "card", "image_box", "icon_image", "title", "description", "price", "button"],
        freshness_score=0.8, design_quality_score=0.85, industry_match_score=0.7,
        uniqueness_score=0.7, popularity_score=0.45,
        estimated_audience_level="niche", brand_popularity="emerging", social_presence="medium",
    ),

    InspirationReference(
        reference_id="cafe_specialty_store_02",
        job_category="website_builder",
        business_type="cafe",
        reference_name="تخصصی قهوه",
        visual_style="product_commerce",
        layout_type="catalog_grid",
        color_palette={"primary": "#78350F", "secondary": "#FED7AA", "accent": "#1F2937"},
        hero_style="split_text_image",
        navigation_style="sticky_simple",
        card_style="flat_bordered",
        section_structure=["navbar", "hero", "about", "menu_grid", "benefits", "form", "footer"],
        interaction_style="subtle_hover",
        best_for=["تخصصی", "دان قهوه", "روست", "بدون شیر"],
        inspiration_notes="تمرکز روی روایت کیفیت دانه/روست قبل از کارت‌های محصول — مناسب کافه‌های تخصصی قهوه.",
        tags=["specialty-coffee", "roast-focused", "expert"],
        editable_layer_requirements=["section", "card", "image_box", "icon_image", "title", "description", "price", "button"],
        freshness_score=0.75, design_quality_score=0.8, industry_match_score=0.9,
        uniqueness_score=0.6, popularity_score=0.5,
        estimated_audience_level="niche", brand_popularity="known", social_presence="medium",
    ),

]


def get_cafe_bank() -> list[InspirationReference]:
    """Return the full cafe inspiration bank (copy not required — read-only use)."""
    return CAFE_INSPIRATION_BANK
